import type { FrameworkControlPlane } from "@/lib/types";

export const SEVENFOLD_ACCESS_ROLES = [
  ["ROLE_SUPER_ADMIN", "Super Admin", "Unrestricted system owner access."],
  ["ROLE_FRAMEWORK_ADMIN", "Framework Admin", "Administers framework settings, approval matrix, workflow access, and framework versions."],
  ["ROLE_TEMPLATE_ADMIN", "Template Admin", "Administers document templates through the Drive/GAS repository adapter."],
  ["ROLE_ACCOUNT_MANAGER", "Account Manager", "Owns lead, opportunity, customer value proposition, and pricing approval."],
  ["ROLE_SOLUTION_ARCHITECT", "Solution Architect", "Owns proposal scenarios, technical assumptions, risks, and solution capability."],
  ["ROLE_COMMERCIAL_MANAGER", "Commercial Manager", "Owns pricing discipline, commercial structure, and cashflow approval."],
  ["ROLE_CONTRACT_LEGAL", "Contract Manager / Legal", "Reviews contracts, PO terms, deviation, liabilities, and legal risks."],
  ["ROLE_SPONSOR", "Sponsor", "Approves SDS, SDOA, project gates, and major change requests."],
  ["ROLE_PROGRAM_DIRECTOR", "Program Director", "Leads high-complexity governance and program execution control."],
  ["ROLE_PROJECT_MANAGER", "Project Manager", "Leads setup, weekly execution tracking, gates, acceptance, handover, and closure."],
  ["ROLE_RESOURCE_MANAGER", "Resource Manager", "Owns resource plan, allocation, onboarding readiness, and resource risk."],
  ["ROLE_PROJECT_FINANCE_MANAGER", "Project Finance Management", "Supports project budget, forecast, net sales, GR, and invoice status."],
  ["ROLE_SUPPLY_MANAGER", "Supply Manager", "Owns supply identification, resource availability, and capacity mitigation."],
  ["ROLE_PROCUREMENT_MANAGER", "Procurement Manager", "Owns purchase request, purchase order, supplier onboarding, and PO status."],
  ["ROLE_HR_ADMINISTRATOR", "HR Administrator", "Owns talent planning import, ratecard base data, and HR administration."],
  ["ROLE_FINANCE_CONTROLLER", "Finance Controller", "Supports opportunity economics, cashflow, and financial sensitivity."],
  ["ROLE_VIEWER", "Viewer", "Read-only business visibility."],
  ["ROLE_AUDITOR", "Auditor", "Read-only audit and compliance visibility."],
] as const;

export function defaultFrameworkControlPlane(): FrameworkControlPlane {
  const roles = SEVENFOLD_ACCESS_ROLES.map(([code, name, description]) => ({
    code,
    name,
    description,
    status: "active",
  }));

  const permissions = [
    ["admin.users.manage", "Manage Users", "administration", "Create, update, deactivate, and scope users."],
    ["admin.roles.manage", "Manage Roles", "administration", "Create and update roles."],
    ["admin.permissions.manage", "Manage Permissions", "administration", "Assign permissions to roles."],
    ["admin.access.manage", "Manage Access Policies", "administration", "Manage user and workflow access policies."],
    ["admin.approval_matrix.manage", "Manage Approval Matrix", "administration", "Manage approval matrices and rules."],
    ["admin.framework_settings.manage", "Manage Framework Settings", "administration", "Manage deal, risk, commodity, currency, and threshold settings."],
    ["admin.templates.manage", "Manage Templates", "documents", "Manage Drive document template references."],
    ["admin.framework_versions.manage", "Manage Framework Versions", "administration", "Create framework version records."],
    ["audit.logs.read", "Read Audit Logs", "audit", "Read audit trail."],
    ["opportunity.manage", "Manage Opportunity", "opportunity", "Create and update opportunity analysis records."],
    ["cashflow.manage", "Manage Cashflow", "cashflow", "Create and approve cashflow options."],
    ["sds.approve", "Approve SDS", "sds", "Approve sales decision for submission."],
    ["sdoa.approve", "Approve SDOA", "sdoa", "Approve PO acknowledgement decisions."],
    ["project.gates.manage", "Manage Project Gates", "project_execution", "Initiate and manage gate movement."],
    ["talent.manage", "Manage Talent Planning", "talent", "Manage talent planning imports and settings."],
    ["ratecard.manage", "Manage Ratecard", "ratecard", "Manage ratecard and blended cost settings."],
  ].map(([code, name, module, description]) => ({ code, name, module, description, status: "active" }));

  return {
    roles,
    permissions,
    rolePermissions: [
      { roleCode: "ROLE_SUPER_ADMIN", permissionCode: "super:all", status: "active" },
      ...permissions.map((permission) => ({ roleCode: "ROLE_FRAMEWORK_ADMIN", permissionCode: permission.code, status: "active" })),
      { roleCode: "ROLE_TEMPLATE_ADMIN", permissionCode: "admin.templates.manage", status: "active" },
      { roleCode: "ROLE_AUDITOR", permissionCode: "audit.logs.read", status: "active" },
    ],
    userAccessPolicies: [
      { id: "super_admin_all", subject: "ROLE_SUPER_ADMIN", subjectType: "role", resourceType: "all", resourceScope: "*", effect: "allow", status: "active" },
      { id: "auditor_read_audit", subject: "ROLE_AUDITOR", subjectType: "role", resourceType: "audit_logs", resourceScope: "read", effect: "allow", status: "active" },
    ],
    workflowAccessPolicies: [
      { id: "opportunity_account_manager", workflow: "Opportunity Analysis", roleCode: "ROLE_ACCOUNT_MANAGER", accessLevel: "owner", status: "active" },
      { id: "opportunity_solution_architect", workflow: "Opportunity Analysis", roleCode: "ROLE_SOLUTION_ARCHITECT", accessLevel: "contributor", status: "active" },
      { id: "cashflow_commercial_manager", workflow: "Cashflow Analysis", roleCode: "ROLE_COMMERCIAL_MANAGER", accessLevel: "owner", status: "active" },
      { id: "sdoa_contract_legal", workflow: "SDOA / PO Acknowledgement", roleCode: "ROLE_CONTRACT_LEGAL", accessLevel: "owner", status: "active" },
      { id: "project_pm", workflow: "Project Execution", roleCode: "ROLE_PROJECT_MANAGER", accessLevel: "owner", status: "active" },
      { id: "talent_hr", workflow: "Talent Planning", roleCode: "ROLE_HR_ADMINISTRATOR", accessLevel: "owner", status: "active" },
    ],
    approvalMatrices: [
      { id: "matrix_sds", workflow: "SDS Approval", decision: "Submit Proposal", status: "active" },
      { id: "matrix_sdoa", workflow: "SDOA / PO Acknowledgement", decision: "Acknowledge PO", status: "active" },
      { id: "matrix_project_gate", workflow: "Project Execution", decision: "Gate Movement", status: "active" },
      { id: "matrix_cashflow", workflow: "Cashflow Analysis", decision: "Approve Cashflow Option", status: "active" },
    ],
    approvalRules: [
      { id: "rule_sds_sponsor", matrixId: "matrix_sds", sequence: "1", approverRole: "ROLE_SPONSOR", condition: "always", required: "true", status: "active" },
      { id: "rule_sdoa_sponsor", matrixId: "matrix_sdoa", sequence: "1", approverRole: "ROLE_SPONSOR", condition: "always", required: "true", status: "active" },
      { id: "rule_gate_sponsor", matrixId: "matrix_project_gate", sequence: "1", approverRole: "ROLE_SPONSOR", condition: "always", required: "true", status: "active" },
      { id: "rule_cashflow_commercial", matrixId: "matrix_cashflow", sequence: "1", approverRole: "ROLE_COMMERCIAL_MANAGER", condition: "always", required: "true", status: "active" },
    ],
    dealTypes: [
      { id: "recurrence", name: "Recurrence", criteria: "Renewal, extension, repeat order, or continuation of known service with low new risk.", maxValueUsd: "50000", status: "active" },
      { id: "small", name: "Small", criteria: "Low complexity, low delivery risk, single country/customer unit, limited legal deviation, value below configurable threshold.", maxValueUsd: "50000", status: "active" },
      { id: "high", name: "High", criteria: "Material financial exposure, cross-functional delivery, complex scope, new solution, multi-site/multi-cluster, or high risk exposure.", minValueUsd: "250000", status: "active" },
      { id: "very_high", name: "Very High", criteria: "Strategic deal, multi-country/global impact, major liability, critical customer, very high contract value, major resource dependency, or severe deviation risk.", minValueUsd: "1000000", sponsorOverride: true, status: "active" },
    ],
    commodityCodes: [
      { code: "HW", name: "Hardware", description: "Hardware, devices, network equipment, servers, and physical materials.", status: "active" },
      { code: "SW", name: "Software", description: "Software license, SaaS subscription, platform, and automation software.", status: "active" },
      { code: "SERV", name: "Services", description: "Professional services, implementation, integration, optimization, and support.", status: "active" },
      { code: "TRAIN", name: "Training", description: "Training, enablement, certification, and knowledge transfer.", status: "active" },
      { code: "MS", name: "Managed Services", description: "Recurring operation, SLA-based managed service, and service desk.", status: "active" },
      { code: "AI", name: "AI", description: "AI/ML automation, analytics, agentic workflow, and model integration.", status: "active" },
      { code: "TM", name: "Time & Material", description: "Resource-based delivery, hourly/monthly rate, and staff augmentation.", status: "active" },
      { code: "DOC", name: "Documentation", description: "Documentation, acceptance pack, handover pack, and controlled deliverables.", status: "active" },
      { code: "PROC", name: "Procurement", description: "Procurement handling, third-party supply, supplier onboarding, and PO administration.", status: "active" },
    ],
    riskDomains: ["Software", "Hardware", "Delivery", "Quality", "Resources", "Contract", "Commercial", "Legal", "Project Management", "Stakeholders", "Security", "Compliance", "Procurement", "Finance"].map((name) => ({
      id: name.toLowerCase().replace(/[^a-z0-9]+/g, "_"),
      name,
      status: "active",
    })),
    riskScoring: [
      { id: "risk_low", label: "Low", minScore: "1", maxScore: "4", severity: "green", actionGuidance: "Track in normal governance cadence.", status: "active" },
      { id: "risk_medium", label: "Medium", minScore: "5", maxScore: "9", severity: "amber", actionGuidance: "Assign owner, mitigation, due date, and review weekly.", status: "active" },
      { id: "risk_high", label: "High", minScore: "10", maxScore: "16", severity: "red", actionGuidance: "Escalate to sponsor/program governance and require mitigation approval.", status: "active" },
      { id: "risk_critical", label: "Critical", minScore: "17", maxScore: "25", severity: "red", actionGuidance: "Executive escalation and formal decision required before next gate.", status: "active" },
    ],
    gateDefinitions: [
      { id: "gate_1", gateCode: "G1", name: "Establishment", description: "Project baseline, team, scope, governance, and delivery controls established.", ownerRole: "ROLE_PROJECT_MANAGER", status: "active" },
      { id: "gate_2", gateCode: "G2", name: "Execution Validation", description: "Execution progress, risk, cost, resource, and quality controls validated.", ownerRole: "ROLE_PROJECT_MANAGER", status: "active" },
      { id: "gate_3", gateCode: "G3", name: "Ready to Acceptance", description: "Deliverables are ready for customer acceptance or GR preparation.", ownerRole: "ROLE_PROJECT_MANAGER", status: "active" },
      { id: "gate_4", gateCode: "G4", name: "Ready to Handover", description: "Acceptance achieved and handover pack is ready.", ownerRole: "ROLE_PROJECT_MANAGER", status: "active" },
      { id: "gate_5", gateCode: "G5", name: "Closure", description: "Invoice, handover, lessons learned, and closure actions completed.", ownerRole: "ROLE_PROGRAM_DIRECTOR", status: "active" },
    ],
    gateChecklist: [
      { id: "g1_scope", gateCode: "G1", item: "Scope baseline approved", mandatory: "true", evidenceType: "SOW", status: "active" },
      { id: "g1_governance", gateCode: "G1", item: "Governance cadence established", mandatory: "true", evidenceType: "Governance Plan", status: "active" },
      { id: "g2_risk", gateCode: "G2", item: "Risk register reviewed", mandatory: "true", evidenceType: "Risk Register", status: "active" },
      { id: "g3_acceptance", gateCode: "G3", item: "Acceptance evidence prepared", mandatory: "true", evidenceType: "Acceptance Certificate", status: "active" },
      { id: "g4_handover", gateCode: "G4", item: "Handover package completed", mandatory: "true", evidenceType: "Handover Pack", status: "active" },
      { id: "g5_invoice", gateCode: "G5", item: "GR and invoice status confirmed", mandatory: "true", evidenceType: "GR/Invoice", status: "active" },
    ],
    governanceCadence: [
      { id: "weekly_project", forum: "Weekly Project Governance", cadence: "weekly", ownerRole: "ROLE_PROJECT_MANAGER", audience: "Project team and delivery stakeholders", status: "active" },
      { id: "biweekly_program", forum: "Bi-weekly Program Governance", cadence: "bi-weekly", ownerRole: "ROLE_PROGRAM_DIRECTOR", audience: "Program leadership", status: "active" },
      { id: "monthly_business", forum: "Monthly Business Review", cadence: "monthly", ownerRole: "ROLE_PROGRAM_DIRECTOR", audience: "Commercial, finance, delivery, sponsor", status: "active" },
      { id: "portfolio_board", forum: "Portfolio Governance Board", cadence: "monthly", ownerRole: "ROLE_SPONSOR", audience: "Portfolio board", status: "active" },
      { id: "quarterly_steerco", forum: "Quarterly Executive Steering Committee", cadence: "quarterly", ownerRole: "ROLE_SPONSOR", audience: "Executive steering committee", status: "active" },
    ],
    ragThresholds: [
      { id: "schedule_variance", metric: "Schedule Variance", green: "<=5%", amber: ">5% and <=15%", red: ">15%", status: "active" },
      { id: "cost_variance", metric: "Cost Variance", green: "<=5%", amber: ">5% and <=10%", red: ">10%", status: "active" },
      { id: "risk_score", metric: "Highest Risk Score", green: "<=4", amber: "5-9", red: ">=10", status: "active" },
      { id: "resource_readiness", metric: "Resource Readiness", green: ">=95%", amber: "80%-94%", red: "<80%", status: "active" },
    ],
    currencies: [
      { code: "USD", name: "US Dollar", rateToUsd: "1", status: "active" },
      { code: "EUR", name: "Euro", rateToUsd: "", status: "active" },
      { code: "IDR", name: "Indonesian Rupiah", rateToUsd: "", status: "active" },
      { code: "SGD", name: "Singapore Dollar", rateToUsd: "", status: "active" },
      { code: "AUD", name: "Australian Dollar", rateToUsd: "", status: "active" },
      { code: "THB", name: "Thai Baht", rateToUsd: "", status: "active" },
    ],
    workingHours: [
      { id: "id_standard", country: "Indonesia", timezone: "Asia/Jakarta", hoursPerDay: "8", daysPerWeek: "5", startTime: "09:00", endTime: "18:00", status: "active" },
      { id: "jp_standard", country: "Japan", timezone: "Asia/Tokyo", hoursPerDay: "8", daysPerWeek: "5", startTime: "09:00", endTime: "18:00", status: "active" },
    ],
    defaultRatecardAssumptions: [
      { id: "management_fee", name: "Management Fee", value: "15", unit: "%", description: "Default management fee applied to resource commercial calculation.", status: "active" },
      { id: "bpjs_kesehatan", name: "BPJS Kesehatan", value: "4", unit: "%", description: "Default employer BPJS Kesehatan assumption.", status: "active" },
      { id: "bpjs_tk", name: "BPJS TK", value: "5.74", unit: "%", description: "Default employer BPJS Ketenagakerjaan blended assumption.", status: "active" },
      { id: "pph23", name: "PPH23", value: "2", unit: "%", description: "Default PPH23 withholding assumption for services.", status: "active" },
    ],
    documentCategories: [
      { id: "templates", category: "Templates", description: "Reusable controlled templates.", retentionRule: "latest_active_plus_history", status: "active" },
      { id: "nda", category: "NDA", description: "Non-disclosure and confidentiality records.", retentionRule: "contract_life_plus_5_years", status: "active" },
      { id: "code_of_ethics", category: "Code of Ethics", description: "Ethics acknowledgment documents.", retentionRule: "employment_life_plus_5_years", status: "active" },
      { id: "cv", category: "CV", description: "Candidate and resource CVs.", retentionRule: "resource_life_plus_3_years", status: "active" },
      { id: "sow", category: "SOW", description: "Statement of work and scope documents.", retentionRule: "project_life_plus_7_years", status: "active" },
      { id: "contract", category: "Contract", description: "Commercial, resource, and legal contract documents.", retentionRule: "contract_life_plus_7_years", status: "active" },
      { id: "acceptance_certificate", category: "Acceptance Certificate", description: "Customer acceptance evidence.", retentionRule: "project_life_plus_7_years", status: "active" },
      { id: "gr", category: "GR", description: "Goods receipt and service acceptance evidence.", retentionRule: "finance_life_plus_7_years", status: "active" },
      { id: "invoice", category: "Invoice", description: "Invoice and billing documents.", retentionRule: "finance_life_plus_7_years", status: "active" },
      { id: "handover", category: "Handover", description: "Project handover package.", retentionRule: "project_life_plus_7_years", status: "active" },
    ],
    workflowStatuses: [
      { id: "opportunity_draft", workflow: "Opportunity Analysis", statusCode: "draft", label: "Draft", terminal: "false", status: "active" },
      { id: "opportunity_ready", workflow: "Opportunity Analysis", statusCode: "ready_for_cashflow", label: "Ready for Cashflow", terminal: "false", status: "active" },
      { id: "cashflow_approved", workflow: "Cashflow Analysis", statusCode: "approved", label: "Approved", terminal: "false", status: "active" },
      { id: "sds_approved", workflow: "SDS Approval", statusCode: "approved", label: "Approved for Submission", terminal: "false", status: "active" },
      { id: "sdoa_acknowledged", workflow: "SDOA / PO Acknowledgement", statusCode: "acknowledged", label: "PO Acknowledged", terminal: "false", status: "active" },
      { id: "project_closed", workflow: "Project Execution", statusCode: "closed", label: "Closed", terminal: "true", status: "active" },
    ],
    approvalThresholds: [
      { id: "sds_small", decision: "SDS", role: "Sponsor", minValueUsd: "0", maxValueUsd: "250000", status: "active" },
      { id: "sds_high", decision: "SDS", role: "Sponsor + Program Director", minValueUsd: "250000", status: "active" },
      { id: "sdoa_all", decision: "SDOA", role: "Sponsor", minValueUsd: "0", status: "active" },
      { id: "gate_movement", decision: "Project Gate Movement", role: "Sponsor", minValueUsd: "0", status: "active" },
    ],
    documentTemplateSettings: ["Templates", "NDA", "Code of Ethics", "CV", "SOW", "Contract", "Acceptance Certificate", "GR", "Invoice", "Handover"].map((category) => ({
      id: category.toLowerCase().replace(/[^a-z0-9]+/g, "_"),
      category,
      documentType: category.toUpperCase().replace(/[^A-Z0-9]+/g, "_"),
      templateName: `${category} Template`,
      status: "active",
    })),
    frameworkVersions: [
      { version: "rev2.0", description: "Business plan Rev2 baseline.", status: "active" },
    ],
    manualNotes: [
      "Risk Analysis Manual, Terminology, and Formula Word document should be generated later by ChatGPT only when Febry requests it.",
      "Cashflow Analysis Manual, Terminology, and Formula Word document should be generated later by ChatGPT only when Febry requests it.",
      "Ratecard Manual, Terminology, and Formula Word document should be generated later by ChatGPT only when Febry requests it.",
    ],
  };
}
